# Generated by Django 4.2.16 on 2026-04-22 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='', max_length=255)),
                ('gstin', models.CharField(blank=True, max_length=20, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(default='India', max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('branches', models.JSONField(default=list)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('sms_provider', models.CharField(default='', max_length=50)),
                ('sms_api_key', models.CharField(default='', max_length=255)),
                ('sms_sender_id', models.CharField(default='', max_length=20)),
                ('sms_template_id', models.CharField(default='', max_length=100)),
                ('sms_templates', models.JSONField(default=dict)),
                ('upi_id', models.CharField(default='', max_length=100)),
                ('upi_display_name', models.CharField(default='', max_length=255)),
                ('upi_enabled', models.BooleanField(default=False)),
                ('upi_supported_apps', models.JSONField(default=list)),
                ('custom_field_schema', models.JSONField(default=list)),
                ('website', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='users.organization')),
            ],
            options={
                'db_table': 'settings',
            },
        ),
    ]
