# Generated by Django 4.2.16 on 2026-04-22 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('customer', 'Customer'), ('supplier', 'Supplier'), ('vendor', 'Vendor')], default='customer', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', models.CharField(max_length=20)),
                ('gstin', models.CharField(blank=True, max_length=20, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(default='India', max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('additional_addresses', models.JSONField(default=list)),
                ('password_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('connection_type', models.CharField(blank=True, max_length=100, null=True)),
                ('package', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('not_paid', 'Not Paid')], default='not_paid', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('upi', 'UPI'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('other', 'Other')], max_length=20, null=True)),
                ('collected_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('collected_by_username', models.CharField(blank=True, max_length=100, null=True)),
                ('box_number', models.CharField(blank=True, max_length=50, null=True)),
                ('stb_number', models.CharField(blank=True, max_length=100, null=True)),
                ('can_caf_id', models.CharField(blank=True, max_length=100, null=True)),
                ('cin', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('permanent_discount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('branch_id', models.IntegerField(blank=True, null=True)),
                ('payment_description', models.TextField(blank=True, null=True)),
                ('payment_updated_at', models.DateTimeField(blank=True, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('tax_number', models.CharField(blank=True, max_length=30, null=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('loyalty_points', models.IntegerField(default=0)),
                ('tags', models.JSONField(default=list)),
                ('custom_fields', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='users.organization')),
            ],
            options={
                'db_table': 'contacts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'contact_type'], name='contacts_organiz_40cb3d_idx'), models.Index(fields=['organization', 'status'], name='contacts_organiz_f03815_idx'), models.Index(fields=['organization', 'payment_status'], name='contacts_organiz_da1e59_idx'), models.Index(fields=['organization', 'mobile'], name='contacts_organiz_b111d7_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(fields=('organization', 'contact_type', 'mobile'), name='unique_org_type_mobile'),
        ),
    ]
