# Generated by Django 4.2.16 on 2026-04-22 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('sales', 'Sales'), ('purchase', 'Purchase'), ('pos', 'POS')], max_length=20)),
                ('invoice_number', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('completed', 'Completed'), ('refunded', 'Refunded'), ('voided', 'Voided')], default='draft', max_length=20)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('branch_id', models.IntegerField(blank=True, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('items', models.JSONField(default=list)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='contacts.contact')),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='users.organization')),
            ],
            options={
                'db_table': 'invoices',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'kind'], name='invoices_organiz_976113_idx'), models.Index(fields=['organization', 'status'], name='invoices_organiz_9b03bf_idx'), models.Index(fields=['contact'], name='invoices_contact_96a8aa_idx'), models.Index(fields=['organization', 'issue_date'], name='invoices_organiz_612bc2_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('organization', 'invoice_number'), name='unique_org_invoice_number'),
        ),
    ]
