# Generated by Django 4.2.16 on 2026-04-22 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('billing_cycle', models.CharField(default='monthly', max_length=20)),
                ('start_date', models.DateField()),
                ('next_billing_date', models.DateField()),
                ('status', models.CharField(default='active', max_length=20)),
                ('auto_renew', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='contacts.contact')),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='users.organization')),
            ],
            options={
                'db_table': 'subscriptions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'status'], name='subscriptio_organiz_4f7e3a_idx'), models.Index(fields=['contact'], name='subscriptio_contact_b3ff7c_idx'), models.Index(fields=['next_billing_date'], name='subscriptio_next_bi_72377a_idx')],
            },
        ),
    ]
