# Generated by Django 4.2.16 on 2026-04-22 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('allowed_modules', models.JSONField(default=list)),
                ('allowed_settings_tabs', models.JSONField(default=list)),
                ('industry_type', models.CharField(default='general', max_length=50)),
                ('terminology', models.JSONField(default=dict)),
                ('subscription_start', models.DateField()),
                ('subscription_end', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'organizations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SignupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('business_type', models.CharField(max_length=100)),
                ('business_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'signup_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(db_column='password_hash', max_length=255)),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('employee', 'Employee')], default='employee', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('allowed_modules', models.JSONField(default=list)),
                ('branch_id', models.IntegerField(blank=True, null=True)),
                ('allowed_permissions', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, db_column='organization_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.organization')),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'role'], name='users_organiz_6045b8_idx')],
            },
        ),
    ]
