# Generated by Django 4.2.16 on 2026-04-22 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_type', models.CharField(choices=[('product', 'Product'), ('isp_category', 'ISP Category'), ('isp_plan', 'ISP Plan')], default='product', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('category_code', models.CharField(blank=True, max_length=50, null=True)),
                ('subcategory', models.CharField(blank=True, max_length=255, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('unit_short_name', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product_form', models.CharField(blank=True, choices=[('physical', 'Physical'), ('service', 'Service'), ('digital', 'Digital'), ('bundle', 'Bundle')], default='physical', max_length=20, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('hsn_sac_code', models.CharField(blank=True, max_length=20, null=True)),
                ('tax_type', models.CharField(choices=[('inclusive', 'Inclusive'), ('exclusive', 'Exclusive'), ('none', 'None')], default='exclusive', max_length=20)),
                ('tax_rate_name', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('warranty_name', models.CharField(blank=True, max_length=100, null=True)),
                ('warranty_duration', models.IntegerField(blank=True, null=True)),
                ('warranty_unit', models.CharField(blank=True, choices=[('days', 'Days'), ('months', 'Months'), ('years', 'Years')], default='months', max_length=20, null=True)),
                ('current_stock', models.IntegerField(default=0)),
                ('stock_alert', models.IntegerField(blank=True, null=True)),
                ('reorder_level', models.IntegerField(blank=True, null=True)),
                ('tracking_type', models.CharField(choices=[('none', 'None'), ('serial', 'Serial'), ('batch', 'Batch')], default='none', max_length=20)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('weight_unit', models.CharField(blank=True, choices=[('g', 'Grams'), ('kg', 'Kilograms'), ('lb', 'Pounds')], max_length=5, null=True)),
                ('expiry_tracking', models.BooleanField(default=False)),
                ('branch_id', models.IntegerField(blank=True, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=100, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('variants', models.JSONField(default=list)),
                ('meta', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='users.organization')),
            ],
            options={
                'db_table': 'inventory',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'catalog_type'], name='inventory_organiz_8a39b4_idx'), models.Index(fields=['organization', 'is_active'], name='inventory_organiz_eb5a98_idx'), models.Index(fields=['organization', 'category'], name='inventory_organiz_76b699_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(condition=models.Q(('sku__isnull', False)), fields=('organization', 'sku'), name='unique_org_sku'),
        ),
    ]
