# Generated by Django 4.2.16 on 2026-04-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('complaint', 'Complaint'), ('connection_request', 'Connection Request'), ('appointment', 'Appointment'), ('service_request', 'Service Request'), ('lead', 'Lead')], max_length=30)),
                ('status', models.CharField(default='new', max_length=50)),
                ('priority', models.CharField(blank=True, max_length=20, null=True)),
                ('assigned_to', models.CharField(blank=True, max_length=255, null=True)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
